### ISSUE TITLE
Disposing Individual Nodes

### ISSUE THREAD

**Issue by vector-man** [platformdotnet/Platform.VirtualFileSystem#12]
It would be nice if you could dispose of nodes individually instead of closing the entire filesystem.

**Comment by tumtumtum** [comment]
Nodes are cached for a period of time and then eventually flushed if they're no longer referenced. Why do you need to dispose of a node manually? If you don't want Nodes to be cached you can change the FileSystemManager to use a NodeCache that doesn't cache :-)

**Comment by vector-man** [comment]
I was concerned about memory leaks, but I wasn't aware that they cleaned up, eventually. I was storing a bunch in a list where they could be added and removed, so calling CloseAllFileSystems wasn't an option for me. Thanks for clearing that up for me.

By the way, do you have an example of changing the node cache?

**Comment by vector-man** [comment]
Problem solved!
