### ISSUE TITLE
Question: Best way to determine node type?

### ISSUE THREAD

**Issue by vector-man** [platformdotnet/Platform.VirtualFileSystem#5]
Hi, I am testing out VirtualFileSystem and I'm really liking it so far.

I'm working on an application, and I need to know before an INode is copied locally (from anywhere else) whether it will save as a file or a folder. Do you know the most reliable way to determine this?

I mean something like the following:

void ProcessData(INode node)
{
// Will the node save as a folder or a file?
// If folder, copy it to local temp folder and process the folder somehow.
// If file, do something else (for example, it may not be supported by this method,)
}

Edit:
I think I may have answered my own question. I guess theNode.NodeType is where you can check if it's a File or Directory. If so, feel free to close this. Thanks.

**Comment by tumtumtum** [comment]
Yeah, NodeType or check if the node "is" IFile.
